name: Publish
on:
  push:
    branches: [ "main" ]
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: |
          echo @web3-plurality:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - run: yarn publish
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.GHCR_TOKEN }}