name: Publish

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
